name: nf-bwa-mem-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::samblaster=0.1.26
  - bioconda::samtools=1.4.1
